# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import document_pb2 as document__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Collaborate = channel.stream_stream(
                '/document.DocumentService/Collaborate',
                request_serializer=document__pb2.Change.SerializeToString,
                response_deserializer=document__pb2.Change.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Collaborate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Collaborate': grpc.stream_stream_rpc_method_handler(
                    servicer.Collaborate,
                    request_deserializer=document__pb2.Change.FromString,
                    response_serializer=document__pb2.Change.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Collaborate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/document.DocumentService/Collaborate',
            document__pb2.Change.SerializeToString,
            document__pb2.Change.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoggingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogChange = channel.unary_unary(
                '/document.LoggingService/LogChange',
                request_serializer=document__pb2.Change.SerializeToString,
                response_deserializer=document__pb2.LogResponse.FromString,
                _registered_method=True)


class LoggingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogChange': grpc.unary_unary_rpc_method_handler(
                    servicer.LogChange,
                    request_deserializer=document__pb2.Change.FromString,
                    response_serializer=document__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.LoggingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.LoggingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoggingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.LoggingService/LogChange',
            document__pb2.Change.SerializeToString,
            document__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
